name: pallon_lastversion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2

  cached_network_image: ^3.3.1

  carousel_slider: ^5.1.1
  flutter_launcher_icons: ^0.14.4
  clipboard: ^2.0.2
  photo_view: ^0.15.0
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.2.0
  intl:
  shared_preferences: ^2.5.3
  mime: ^2.0.0
  flutter_phoenix: ^1.1.1
  timeago: ^3.7.1
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.0.2
  googleapis_auth: ^2.0.0
  dash_chat_2: ^0.0.21
#  google_sign_in: ^7.2.0


  flutter_local_notifications: ^17.0.0

  url_strategy: ^0.3.0
  googleapis: ^15.0.0
  http: ^1.5.0

  device_calendar: ^4.3.3
  location: ^8.0.1
  path_provider: ^2.1.5
  excel: ^4.0.6
  pdf: ^3.11.3
  share_plus: ^12.0.0
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.9
  dio: ^5.4.0
  google_sign_in: 6.2.1
  permission_handler: ^11.2.0
  url_launcher: ^6.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/Utils/assets/images/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/Utils/assets/Images/
    - lib/core/Utils/assets/lang/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf